### ISSUE TITLE
[search] Pelias API field deprecation

### ISSUE THREAD

**Issue by missinglink** [mapzen/pelias-android-sdk#6]
As a follow up to this issue: https://github.com/mapzen/open/issues/358

**we don't use this property so I believe it should work just fine**
I think you'll find it's being used to derive the doc ids, in places such as:
https://github.com/mapzen/pelias-android-sdk/blob/68e036553f68af8b33227abdd195bcb8ba2e9e3e/src/main/java/com/mapzen/android/Pelias.java#L55

**Ping me when you have a development build out for it so we can verify that**
Due to the financial cost and complexity of running the prod cluster we don't currently have a staging env and probably won't ever have one, when you are happy with what is currently live I will kill the `type` property.

[edit] scratch that, we could potentially deploy a custom `pelias/api` repo to a box in the live env to test against if you find it helpful, it would require a bit of @heffergm 's time, so let us know if you need that.

**Comment by missinglink** [comment]
FYI: @baldur @ecgreb this is going to be released imminently.

**Comment by baldur** [comment]
@missinglink we aren't using the doc endpoint any more ... so there is no need for another build. Is everyone comfortable with older versions of the open application breaking?

**Comment by mjcunningham** [comment]
There are only around 20 people who this will be an issue for. No big deal.

**Comment by baldur** [comment]
rad ... closing this issue then
